pipeline:
  agent any
  
  stages:
    - stage: "Clonage"
      steps:
        - script:
            git clone https://github.com/marafa-hamidou/DEVOPS.git
            cd votre-repo
    
    - stage: "Image"
      steps:
        - script:
            cd votre-repo
            docker build -t marafa-flask-app .
    
    - stage: "Publication"
      steps:
        - script:
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag marafa-flask-app marafa1234/docker-flask-app:latest
            docker push marafa1234/docker-flask-app:latest
