pipeline:
  agent any

  stages:
    - stage: "Clonage du projet"
      steps:
        - script:
            sh 'git clone https://github.com/marafa-hamidou/DEVOPS'

    - stage: "Fix permissions Docker"
      steps:
        - script:
            sh 'sudo chmod 666 /var/run/docker.sock'

    - stage: "Construction de l'image Docker"
      steps:
        - script:
            sh 'docker build -t marafa1234/docker-flask-app DEVOPS/'

    - stage: "Connexion à Docker Hub"
      steps:
        - script:
            sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'

    - stage: "Publication de l'image"
      steps:
        - script:
            sh 'docker push marafa1234/docker-flask-app'
