pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = 'dockerhub-credentials'  // Remplace par l'ID de tes credentials DockerHub dans Jenkins
        DOCKER_IMAGE = 'marafa1234/docker-flask-app:latest'
        GIT_REPO = 'https://github.com/marafa-hamidou/DEVOPS' // Remplace par ton vrai dépôt GitHub
    }

    stages {
        stage('Clonage') {
            steps {
                git branch: 'main', url: "${GIT_REPO}"
            }
        }

        stage('Construction de l’image') {
            steps {
                script {
                    sh 'docker build -t marafa-flask-app .'
                }
            }
        }

        stage('Authentification DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    }
                }
            }
        }

        stage('Tag et Push de l’image') {
            steps {
                script {
                    sh 'docker tag marafa-flask-app ${DOCKER_IMAGE}'
                    sh 'docker push ${DOCKER_IMAGE}'
                }
            }
        }
    }
}
