pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "marafa1234/docker-flask-app"  // Remplace "ton_nom" par ton nom Docker Hub
        GITHUB_REPO = "https://github.com/marafa-hamidou/DEVOPS"  // Remplace par ton URL GitHub
    }

    stages {
        stage('Clonage du projet') {
            steps {
                script {
                    sh 'git clone $GITHUB_REPO'
                    sh 'ls -la DEVOPS' // Vérifie que le clonage a fonctionné
                }
            }
        }

        stage('Construction de l\'image Docker') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE DEVOPS/'
                }
            }
        }

        stage('Connexion à Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PASSWORD')]) {
                        sh 'echo $DOCKER_PASSWORD | docker login -u ton_nom --password-stdin'
                    }
                }
            }
        }

        stage('Publication de l\'image') {
            steps {
                script {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
    }
}
